apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: springbootremotedebug-container
          image: docker.io/trukhinyuri/springbootremotedebug:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080

